# Based on: https://github.com/hvr/multi-ghc-travis
# and:      https://raw.githubusercontent.com/haskell-suite/haskell-src-exts/master/.travis.yml

cache:
  directories:
    - .cabal-sandbox

env:
 - CABALVER=1.18 GHCVER=7.6.3
 - CABALVER=1.18 GHCVER=7.8.3
 - CABALVER=1.22 GHCVER=7.10.1

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER happy-1.19.3 alex-3.1.4
 - export PATH=/opt/happy/1.19.3/bin:/opt/alex/3.1.4/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal sandbox init
 - git clone https://github.com/emilaxelsson/language-c-quote.git
 - cd language-c-quote
 - git checkout no-haskell-src-meta
 - cd ..
 - cabal sandbox add-source language-c-quote
 - cabal install -f-full-haskell-antiquotes language-c-quote
 - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
 - cabal configure --enable-tests --enable-benchmarks -v2
 - cabal build
 - cabal test
 - cabal check
 - cabal sdist
 - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal sandbox init --sandbox ../.cabal-sandbox;
      cabal install --force-reinstalls "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi
